server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger.html

spring:
  application:
    name: myco

  h2:
    console:
      # The context path must be added here as well for H2 console to be accessible
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/myco;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
#  sql:
#    init:
#      mode: embedded

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  web:
    resources:
      static-locations: file:///${file.upload-dir}

    cors:
      allowed-origins: "*" # Allow requests from any origin
      allowed-methods: "*" # Allow all HTTP methods (GET, POST, etc.)
      allowed-headers: "*" # Allow all headers

# Use environment variables for external URLs and paths, with local fallbacks.
file:
  upload-dir: ${FILE_UPLOAD_DIR:D:/GitProject/uploads/}
  access-location: ${APP_BASE_URL:http://localhost:8080}/

qr:
  searchUrl: ${APP_BASE_URL:http://localhost:8080}/
