spring:
  datasource:
    url: jdbc:h2:file:/data/myco;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
#  sql:
#    init:
#      mode: embedded


  web:
    resources:
      static-locations: file:///${file.upload-dir}

file:
  upload-dir: ${FILE_UPLOAD_DIR:D:/GitProject/uploads/}
  access-location: ${APP_BASE_URL:http://localhost:8080}/

qr:
  searchUrl: ${APP_BASE_URL:http://localhost:8080}/
